# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Domain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Domain
  pod 'RxSwift', '~> 5.0'
end

target 'ApiPlatform' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkPlatform
  pod 'RxSwift', '~> 5.0'
  pod 'RxAlamofire'
  pod 'SwiftHash'
end

target 'ApiPlatformTests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkPlatform
  pod 'RxSwift', '~> 5.0'
  pod 'RxAlamofire'
  pod 'SwiftHash'
end

target 'SuperHeroList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SuperHeroList
  pod 'RxSwift', '~> 5.0'
  pod 'RxCocoa', '~> 5.0'
  pod 'UIScrollView-InfiniteScroll'

end

target 'SuperHeroListTests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SuperHeroList
  pod 'RxSwift', '~> 5.0'
  pod 'RxCocoa', '~> 5.0'
  pod 'RxTest'
  pod 'UIScrollView-InfiniteScroll'
end
